<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1520419741307" stop="1520419793472" version="1.4.8">
    <name>Default suite</name>
    <title>Default suite : Default test[]</title>
    <test-cases>
        <test-case start="1520419764301" stop="1520419764304" status="canceled">
            <name>validateLogin</name>
            <failure>
                <message>RuntimeException: Can't invoke method public java.lang.Object[][] com.infy.utils.Utils.readDatafromExcel(java.lang.reflect.Method) on this instance of class com.infy.login.EbayTestCases due to class mismatch</message>
                <stack-trace>java.lang.RuntimeException: Can't invoke method public java.lang.Object[][] com.infy.utils.Utils.readDatafromExcel(java.lang.reflect.Method) on this instance of class com.infy.login.EbayTestCases due to class mismatch
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="CHDSEZ97152L.local"/>
                <label name="thread" value="26601@CHDSEZ97152L.local.main"/>
            </labels>
        </test-case>
        <test-case start="1520419764317" stop="1520419793471" status="broken">
            <name>validateSearchItem</name>
            <failure>
                <message>Test was interrupted</message>
            </failure>
            <labels>
                <label name="host" value="CHDSEZ97152L.local"/>
                <label name="thread" value="26601@CHDSEZ97152L.local.main"/>
            </labels>
        </test-case>
        <test-case start="1520419764317" stop="1520419793471" status="broken">
            <name>validateSearchItem</name>
            <failure>
                <message>Test was interrupted</message>
            </failure>
            <labels>
                <label name="host" value="CHDSEZ97152L.local"/>
                <label name="thread" value="26601@CHDSEZ97152L.local.main"/>
            </labels>
        </test-case>
        <test-case start="1520419741307" stop="1520419793471" status="broken">
            <name>Default suite</name>
            <title>Default suite</title>
            <failure>
                <message>Test suite was interrupted, some test cases may be lost</message>
            </failure>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
